# Generated by Django 4.0.2 on 2022-02-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0003_question_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='date_created',
        ),
    ]
